-- 렌트 테이블 생성
CREATE TABLE tbl_rent_book (

    RENT_SEQ	NUMBER	NOT NULL	PRIMARY KEY,
    RENT_DATE	VARCHAR2(10)	NOT NULL,	
    RENT_RETURN_DATE	VARCHAR2(10)	NOT NULL,
    RENT_BCODE	VARCHAR2(6)	NOT NULL,	
    RENT_UCODE	VARCHAR2(6)	NOT NULL,	
    RENT_RETUR_YN	VARCHAR2(1),		
    RENT_POINT	NUMBER		

);
-- 시퀀스 생성
CREATE SEQUENCE SEQ_RENT
START WITH 1 INCREMENT BY 1;

-- SELECT SEQ_RENT.NEXTVAL FROM DUAL;

CREATE TABLE tbl_books (

    B_CODE	VARCHAR2(6)	NOT NULL	PRIMARY KEY,
    B_NAME	nVARCHAR2(125)	NOT NULL,	
    B_AUTHER	nVARCHAR2(125)	NOT NULL,	
    B_COMP	nVARCHAR2(125),		
    B_YEAR	NUMBER	NOT NULL,	
    B_IPRICE	NUMBER,		
    B_RPRICE	NUMBER	NOT NULL	

);

CREATE TABLE tbl_users (

    U_CODE	VARCHAR2(6)	NOT NULL	PRIMARY KEY,
    U_NAME	nVARCHAR2(125)	NOT NULL,	
    U_TEL	nVARCHAR2(125),		
    U_ADDR	nVARCHAR2(125)		

);
-- 렌트 테이블과 북 테이블 FK 지정
ALTER TABLE tbl_rent_book
ADD CONSTRAINT FK_BOOK
FOREIGN KEY(rent_bcode)
REFERENCES tbl_books(b_code);

-- 렌트 테이블과 유저 테이블 FK 지정
ALTER TABLE tbl_rent_book
ADD CONSTRAINT FK_USER
FOREIGN KEY(rent_ucode)
REFERENCES tbl_users(u_code);


